using Jotunn.Configs;
using UnityEngine;

namespace BrudvikWhiteHilt.Items.Foraging.Madder;

/// <summary>
/// Madder, a scrambling plant with whorls of narrow leaves on the Plains; its roots give the red of Viking cloth.
/// Model: generated by AssetSource/Tools/make_forage_models.py, with the roots as the item. Cloudberry bushes picked on
/// the Plains can also give it.
/// </summary>
public class Madder : ForageableBase
{
    /// <summary>
    /// Prefab name of the madder root item.
    /// </summary>
    public const string PrefabName = "WhiteHiltMadder";

    /// <inheritdoc/>
    public override string BaseName => PrefabName;

    /// <inheritdoc/>
    protected override string FullName => "Madder Root";

    /// <inheritdoc/>
    protected override string Description => "Twisted red roots of the madder plant. Boiled, they give the warm red that Viking chieftains wore.";

    /// <inheritdoc/>
    protected override string CopyItemFrom => "Thistle";

    /// <inheritdoc/>
    protected override string CopyPickableFrom => "Pickable_Dandelion";

    /// <inheritdoc/>
    protected override VegetationConfig Vegetation => new()
    {
        Biome = Heightmap.Biome.Plains,
        Max = 1.5f,
        GroupSizeMin = 1,
        GroupSizeMax = 3,
        GroupRadius = 3f,
        MinAltitude = 1f,
        MaxTilt = 25f,
        ScaleMin = 0.85f,
        ScaleMax = 1.15f,
        BlockCheck = true
    };

    /// <inheritdoc/>
    public override bool Enabled => true;

    /// <inheritdoc/>
    protected override string ExtraDropFrom => "CloudberryBush";

    /// <inheritdoc/>
    protected override float ExtraDropChance => 0.15f;

    /// <inheritdoc/>
    protected override void ApplyVisual(GameObject visualRoot)
    {
        ReplacePlantMesh(visualRoot, IsItem(visualRoot) ? "madderroot" : "madder", 0.27f);
    }
}
