using Jotunn.Configs;
using UnityEngine;

namespace BrudvikWhiteHilt.Items.Foraging.IcelandMoss;

/// <summary>
/// Iceland moss, a curly brown lichen of the Mountain heath that is boiled into porridge and bread in hard winters.
/// Model: generated by AssetSource/Tools/make_forage_models.py. Wild onions picked in the Mountains can also give it.
/// </summary>
public class IcelandMoss : ForageableBase
{
    /// <summary>
    /// Prefab name of the Iceland moss item.
    /// </summary>
    public const string PrefabName = "WhiteHiltIcelandMoss";

    /// <inheritdoc/>
    public override string BaseName => PrefabName;

    /// <inheritdoc/>
    protected override string FullName => "Iceland Moss";

    /// <inheritdoc/>
    protected override string Description => "A tough, curly lichen from the mountain heath. Boiled long, it turns into a bitter but filling porridge.";

    /// <inheritdoc/>
    protected override string CopyItemFrom => "Thistle";

    /// <inheritdoc/>
    protected override string CopyPickableFrom => "Pickable_Mushroom";

    /// <inheritdoc/>
    protected override VegetationConfig Vegetation => new()
    {
        Biome = Heightmap.Biome.Mountain,
        // Groups per zone where the ground suits it; the generator keeps trying spots until they are placed.
        Min = 1,
        Max = 2,
        ForcePlacement = true,
        GroupSizeMin = 2,
        GroupSizeMax = 4,
        GroupRadius = 3f,
        MinAltitude = 1f,
        MaxTilt = 30f,
        ScaleMin = 0.8f,
        ScaleMax = 1.2f,
        BlockCheck = true
    };

    /// <inheritdoc/>
    public override bool Enabled => true;

    /// <inheritdoc/>
    protected override string ExtraDropFrom => "Pickable_SeedOnion";

    /// <inheritdoc/>
    protected override float ExtraDropChance => 0.15f;

    /// <inheritdoc/>
    protected override void ApplyVisual(GameObject visualRoot)
    {
        ReplacePlantMesh(visualRoot, "icelandmoss", 0.15f);
    }
}
