using Jotunn.Configs;
using UnityEngine;

namespace BrudvikWhiteHilt.Items.Foraging.Angelica;

/// <summary>
/// Angelica, a tall herb with green flower globes in the Mountains. The Vikings grew it in walled gardens and traded it,
/// and chewed the stalks for strength. Model: generated by AssetSource/Tools/make_forage_models.py.
/// Wild onions picked in the Mountains can also give it.
/// </summary>
public class Angelica : ForageableBase
{
    /// <summary>
    /// Prefab name of the angelica item.
    /// </summary>
    public const string PrefabName = "WhiteHiltAngelica";

    /// <inheritdoc/>
    public override string BaseName => PrefabName;

    /// <inheritdoc/>
    protected override string FullName => "Angelica";

    /// <inheritdoc/>
    protected override string Description => "A tall, sweet-smelling herb with green flower globes. Vikings grew it in walled gardens and chewed the stalks for strength.";

    /// <inheritdoc/>
    protected override string CopyItemFrom => "Thistle";

    /// <inheritdoc/>
    protected override string CopyPickableFrom => "Pickable_Thistle";

    /// <inheritdoc/>
    protected override VegetationConfig Vegetation => new()
    {
        Biome = Heightmap.Biome.Mountain,
        Max = 1.5f,
        GroupSizeMin = 1,
        GroupSizeMax = 3,
        GroupRadius = 3f,
        MinAltitude = 1f,
        MaxTilt = 30f,
        ScaleMin = 0.85f,
        ScaleMax = 1.15f,
        BlockCheck = true
    };

    /// <inheritdoc/>
    public override bool Enabled => true;

    /// <inheritdoc/>
    protected override string ExtraDropFrom => "Pickable_SeedOnion";

    /// <inheritdoc/>
    protected override float ExtraDropChance => 0.2f;

    /// <inheritdoc/>
    protected override void ApplyVisual(GameObject visualRoot)
    {
        ReplacePlantMesh(visualRoot, "angelica", 1.5f);
    }

    /// <inheritdoc/>
    protected override void ApplyPickableVisual(GameObject pickablePrefab, Pickable pickable)
    {
        RemoveGlow(pickablePrefab);
        base.ApplyPickableVisual(pickablePrefab, pickable);
    }
}
