using Jotunn.Configs;
using UnityEngine;

namespace BrudvikWhiteHilt.Items.Foraging.WolfLichen;

/// <summary>
/// Wolf lichen, bright yellow tufts on dead branches in the Mountains. Hunters mixed it into bait to poison wolves.
/// Model: generated by AssetSource/Tools/make_forage_models.py; the branch stays and the lichen grows back.
/// Wolves sometimes carry it in their fur.
/// </summary>
public class WolfLichen : ForageableBase
{
    /// <summary>
    /// Prefab name of the wolf lichen item.
    /// </summary>
    public const string PrefabName = "WhiteHiltWolfLichen";

    /// <inheritdoc/>
    public override string BaseName => PrefabName;

    /// <inheritdoc/>
    protected override string FullName => "Wolf Lichen";

    /// <inheritdoc/>
    protected override string Description => "Bright yellow lichen from dead mountain pines. Hunters mixed it into bait to poison wolves; a rune can carry its bane.";

    /// <inheritdoc/>
    protected override string CopyItemFrom => "Thistle";

    /// <inheritdoc/>
    protected override string CopyPickableFrom => "Pickable_Mushroom";

    /// <inheritdoc/>
    protected override VegetationConfig Vegetation => new()
    {
        Biome = Heightmap.Biome.Mountain,
        // Groups per zone where the ground suits it; the generator keeps trying spots until they are placed.
        Min = 1,
        Max = 1,
        ForcePlacement = true,
        GroupSizeMin = 1,
        GroupSizeMax = 2,
        GroupRadius = 4f,
        MinAltitude = 1f,
        MaxTilt = 25f,
        ScaleMin = 0.9f,
        ScaleMax = 1.2f,
        BlockCheck = true
    };

    /// <inheritdoc/>
    public override bool Enabled => true;

    /// <inheritdoc/>
    protected override string ExtraDropFrom => null;

    /// <inheritdoc/>
    protected override string CreatureDropFrom => "Wolf";

    /// <inheritdoc/>
    protected override float CreatureDropChance => 0.1f;

    /// <inheritdoc/>
    protected override void ApplyVisual(GameObject visualRoot)
    {
        ReplacePlantMesh(visualRoot, "wolflichenitem", 0.1f);
    }

    /// <inheritdoc/>
    protected override void ApplyPickableVisual(GameObject pickablePrefab, Pickable pickable)
    {
        ReplaceBushMesh(pickablePrefab, pickable, "wolflichen", 0.32f);
    }
}
