using Jotunn.Configs;
using UnityEngine;

namespace BrudvikWhiteHilt.Items.Foraging.Woad;

/// <summary>
/// Woad, blue-green leaves and sprays of yellow flowers on the Plains. Its fermented leaves give the deep blue dye that
/// was found in the Oseberg ship. Model: generated by AssetSource/Tools/make_forage_models.py. Wild flax picked on the
/// Plains can also give it.
/// </summary>
public class Woad : ForageableBase
{
    /// <summary>
    /// Prefab name of the woad item.
    /// </summary>
    public const string PrefabName = "WhiteHiltWoad";

    /// <inheritdoc/>
    public override string BaseName => PrefabName;

    /// <inheritdoc/>
    protected override string FullName => "Woad";

    /// <inheritdoc/>
    protected override string Description => "Blue-green leaves under sprays of yellow flowers. Crushed and left to sour, the leaves give the deepest blue a dyer knows.";

    /// <inheritdoc/>
    protected override string CopyItemFrom => "Thistle";

    /// <inheritdoc/>
    protected override string CopyPickableFrom => "Pickable_Thistle";

    /// <inheritdoc/>
    protected override VegetationConfig Vegetation => new()
    {
        Biome = Heightmap.Biome.Plains,
        // Groups per zone where the ground suits it; the generator keeps trying spots until they are placed.
        Min = 1,
        Max = 2,
        ForcePlacement = true,
        GroupSizeMin = 1,
        GroupSizeMax = 3,
        GroupRadius = 3f,
        MinAltitude = 1f,
        MaxTilt = 25f,
        ScaleMin = 0.85f,
        ScaleMax = 1.15f,
        BlockCheck = true
    };

    /// <inheritdoc/>
    public override bool Enabled => true;

    /// <inheritdoc/>
    protected override string ExtraDropFrom => "Pickable_Flax_Wild";

    /// <inheritdoc/>
    protected override float ExtraDropChance => 0.15f;

    /// <inheritdoc/>
    protected override void ApplyVisual(GameObject visualRoot)
    {
        ReplacePlantMesh(visualRoot, "woad", 0.9f);
    }

    /// <inheritdoc/>
    protected override void ApplyPickableVisual(GameObject pickablePrefab, Pickable pickable)
    {
        RemoveGlow(pickablePrefab);
        base.ApplyPickableVisual(pickablePrefab, pickable);
    }
}
