using BrudvikWhiteHilt.Helpers;
using Jotunn.Configs;
using UnityEngine;

namespace BrudvikWhiteHilt.Items.Foraging.LabradorTea;

/// <summary>
/// Marsh Labrador tea, a low evergreen shrub of the Swamp hummocks with domes of white flowers. Its strong smell keeps
/// biting insects away. Model: generated by AssetSource/Tools/make_forage_models.py; the flowers hide when picked.
/// Thistles picked in the Swamp can also give it.
/// </summary>
public class LabradorTea : ForageableBase
{
    /// <summary>
    /// Prefab name of the Labrador tea item.
    /// </summary>
    public const string PrefabName = "WhiteHiltLabradorTea";

    /// <inheritdoc/>
    public override string BaseName => PrefabName;

    /// <inheritdoc/>
    protected override string FullName => "Labrador Tea";

    /// <inheritdoc/>
    protected override string Description => "Leathery leaves and white flower heads from a low bog shrub. The smell is sharp enough to keep gnats and leeches off you.";

    /// <inheritdoc/>
    protected override string CopyItemFrom => "Thistle";

    /// <inheritdoc/>
    protected override string CopyPickableFrom => "BlueberryBush";

    /// <inheritdoc/>
    protected override VegetationConfig Vegetation => new()
    {
        Biome = Heightmap.Biome.Swamp,
        // Groups per zone where the ground suits it; the generator keeps trying spots until they are placed.
        Min = 1,
        Max = 2,
        ForcePlacement = true,
        GroupSizeMin = 1,
        GroupSizeMax = 3,
        GroupRadius = 4f,
        MinAltitude = 0.5f,
        MaxTilt = 20f,
        ScaleMin = 0.8f,
        ScaleMax = 1.1f,
        BlockCheck = true
    };

    /// <inheritdoc/>
    public override bool Enabled => true;

    /// <inheritdoc/>
    protected override string ExtraDropFrom => "Pickable_Thistle";

    /// <inheritdoc/>
    protected override float ExtraDropChance => 0.2f;

    /// <inheritdoc/>
    protected override void ApplyVisual(GameObject visualRoot)
    {
        // The purple thistle flowers turn into white flower heads.
        VisualHelper.RecolorHue(visualRoot, 0.72f, 0.95f, 0.2f, 0.12f, 1.7f);
    }

    /// <inheritdoc/>
    protected override void ApplyPickableVisual(GameObject pickablePrefab, Pickable pickable)
    {
        ReplaceBushMesh(pickablePrefab, pickable, "labradortea", 0.65f);
    }
}
