using Jotunn.Configs;
using UnityEngine;

namespace BrudvikWhiteHilt.Items.Foraging.SphagnumMoss;

/// <summary>
/// Sphagnum moss, red and green cushions on the wet ground of the Swamp. Vikings packed wounds with it, so it goes into
/// healing drinks. Model: generated by AssetSource/Tools/make_forage_models.py.
/// Red mushrooms picked in the Swamp can also give it.
/// </summary>
public class SphagnumMoss : ForageableBase
{
    /// <summary>
    /// Prefab name of the sphagnum moss item.
    /// </summary>
    public const string PrefabName = "WhiteHiltSphagnumMoss";

    /// <inheritdoc/>
    public override string BaseName => PrefabName;

    /// <inheritdoc/>
    protected override string FullName => "Sphagnum Moss";

    /// <inheritdoc/>
    protected override string Description => "A soft cushion of red and green bog moss. It soaks up blood and keeps a wound clean.";

    /// <inheritdoc/>
    protected override string CopyItemFrom => "Thistle";

    /// <inheritdoc/>
    protected override string CopyPickableFrom => "Pickable_Mushroom";

    /// <inheritdoc/>
    protected override VegetationConfig Vegetation => new()
    {
        Biome = Heightmap.Biome.Swamp,
        Max = 2,
        GroupSizeMin = 2,
        GroupSizeMax = 4,
        GroupRadius = 3f,
        MinAltitude = 0.2f,
        MaxTilt = 20f,
        ScaleMin = 0.8f,
        ScaleMax = 1.2f,
        BlockCheck = true
    };

    /// <inheritdoc/>
    public override bool Enabled => true;

    /// <inheritdoc/>
    protected override string ExtraDropFrom => "Pickable_Mushroom";

    /// <inheritdoc/>
    protected override float ExtraDropChance => 0.25f;

    /// <inheritdoc/>
    protected override void ApplyVisual(GameObject visualRoot)
    {
        ReplacePlantMesh(visualRoot, "sphagnum", 0.1f);
    }
}
