using Jotunn.Configs;
using UnityEngine;

namespace BrudvikWhiteHilt.Items.Foraging.MountainSorrel;

/// <summary>
/// Mountain sorrel, round sour leaves and red seed spikes on damp ledges in the Mountains, eaten fresh against winter
/// sickness. Model: generated by AssetSource/Tools/make_forage_models.py. Wild onions picked in the Mountains can also
/// give it.
/// </summary>
public class MountainSorrel : ForageableBase
{
    /// <summary>
    /// Prefab name of the mountain sorrel item.
    /// </summary>
    public const string PrefabName = "WhiteHiltMountainSorrel";

    /// <inheritdoc/>
    public override string BaseName => PrefabName;

    /// <inheritdoc/>
    protected override string FullName => "Mountain Sorrel";

    /// <inheritdoc/>
    protected override string Description => "Round, sour leaves and red seed spikes from damp mountain ledges. Eaten fresh, it keeps the winter sickness away.";

    /// <inheritdoc/>
    protected override string CopyItemFrom => "Thistle";

    /// <inheritdoc/>
    protected override string CopyPickableFrom => "Pickable_Dandelion";

    /// <inheritdoc/>
    protected override VegetationConfig Vegetation => new()
    {
        Biome = Heightmap.Biome.Mountain,
        // Groups per zone where the ground suits it; the generator keeps trying spots until they are placed.
        Min = 1,
        Max = 2,
        ForcePlacement = true,
        GroupSizeMin = 2,
        GroupSizeMax = 5,
        GroupRadius = 3f,
        MinAltitude = 1f,
        MaxTilt = 40f,
        ScaleMin = 0.85f,
        ScaleMax = 1.15f,
        BlockCheck = true
    };

    /// <inheritdoc/>
    public override bool Enabled => true;

    /// <inheritdoc/>
    protected override string ExtraDropFrom => "Pickable_SeedOnion";

    /// <inheritdoc/>
    protected override float ExtraDropChance => 0.25f;

    /// <inheritdoc/>
    protected override void ApplyVisual(GameObject visualRoot)
    {
        ReplacePlantMesh(visualRoot, "mountainsorrel", 0.3f);
    }
}
