using Jotunn.Configs;
using Jotunn.Entities;
using Jotunn.Managers;
using UnityEngine;

namespace BrudvikWhiteHilt.Items.Foraging.BogIron;

/// <summary>
/// Bog iron, rust-brown lumps in the mud and shallow water of the Swamp, where the water has gathered iron for years.
/// The smelter turns each lump into iron, as the Vikings got most of theirs. Model: generated by
/// AssetSource/Tools/make_forage_models.py.
/// </summary>
public class BogIron : ForageableBase
{
    /// <summary>
    /// Prefab name of the bog iron item.
    /// </summary>
    public const string PrefabName = "WhiteHiltBogIron";

    /// <inheritdoc/>
    public override string BaseName => PrefabName;

    /// <inheritdoc/>
    protected override string FullName => "Bog Iron";

    /// <inheritdoc/>
    protected override string Description => "Rust-brown lumps from the bottom of the bog, where the water has gathered iron for years. Smelt them into iron.";

    /// <inheritdoc/>
    protected override string CopyItemFrom => "IronScrap";

    /// <inheritdoc/>
    protected override string CopyPickableFrom => "Pickable_Stone";

    /// <inheritdoc/>
    protected override VegetationConfig Vegetation => new()
    {
        Biome = Heightmap.Biome.Swamp,
        Max = 1.5f,
        GroupSizeMin = 1,
        GroupSizeMax = 2,
        GroupRadius = 2f,
        MinAltitude = -1f,
        MaxAltitude = 0.3f,
        MaxTilt = 25f,
        ScaleMin = 0.9f,
        ScaleMax = 1.2f,
        BlockCheck = true
    };

    /// <inheritdoc/>
    public override bool Enabled => true;

    /// <inheritdoc/>
    protected override string ExtraDropFrom => null;

    /// <inheritdoc/>
    protected override void ApplyVisual(GameObject visualRoot)
    {
        ReplacePlantMesh(visualRoot, IsItem(visualRoot) ? "bogironlump" : "bogiron", 0.1f);
    }

    /// <inheritdoc/>
    protected override void OnAdded()
    {
        ItemManager.Instance.AddItemConversion(new CustomItemConversion(new SmelterConversionConfig
        {
            Station = Smelters.Smelter,
            FromItem = PrefabName,
            ToItem = "Iron"
        }));
    }
}
