using Jotunn.Configs;
using UnityEngine;

namespace BrudvikWhiteHilt.Items.Foraging.Caraway;

/// <summary>
/// Caraway, slender stems with umbrellas of white flowers on the Plains; its seeds are the old northern spice for bread,
/// cheese and meat. Model: generated by AssetSource/Tools/make_forage_models.py. Wild barley picked on the Plains can also
/// give it.
/// </summary>
public class Caraway : ForageableBase
{
    /// <summary>
    /// Prefab name of the caraway item.
    /// </summary>
    public const string PrefabName = "WhiteHiltCaraway";

    /// <inheritdoc/>
    public override string BaseName => PrefabName;

    /// <inheritdoc/>
    protected override string FullName => "Caraway";

    /// <inheritdoc/>
    protected override string Description => "Slender stems with umbrellas of tiny white flowers and seeds that smell of anise. The spice of the north for bread, cheese and sausage.";

    /// <inheritdoc/>
    protected override string CopyItemFrom => "Thistle";

    /// <inheritdoc/>
    protected override string CopyPickableFrom => "Pickable_Dandelion";

    /// <inheritdoc/>
    protected override VegetationConfig Vegetation => new()
    {
        Biome = Heightmap.Biome.Plains,
        Max = 2,
        GroupSizeMin = 2,
        GroupSizeMax = 4,
        GroupRadius = 3f,
        MinAltitude = 1f,
        MaxTilt = 25f,
        ScaleMin = 0.85f,
        ScaleMax = 1.15f,
        BlockCheck = true
    };

    /// <inheritdoc/>
    public override bool Enabled => true;

    /// <inheritdoc/>
    protected override string ExtraDropFrom => "Pickable_Barley_Wild";

    /// <inheritdoc/>
    protected override float ExtraDropChance => 0.2f;

    /// <inheritdoc/>
    protected override void ApplyVisual(GameObject visualRoot)
    {
        ReplacePlantMesh(visualRoot, "caraway", 0.54f);
    }
}
