using Jotunn.Configs;
using UnityEngine;

namespace BrudvikWhiteHilt.Items.Foraging.Yarrow;

/// <summary>
/// Yarrow, feathery leaves and flat white flower heads on the Plains. The soldier's wound herb, and a bittering herb for
/// gruit ale. Model: generated by AssetSource/Tools/make_forage_models.py. Wild flax picked on the Plains can also give it.
/// </summary>
public class Yarrow : ForageableBase
{
    /// <summary>
    /// Prefab name of the yarrow item.
    /// </summary>
    public const string PrefabName = "WhiteHiltYarrow";

    /// <inheritdoc/>
    public override string BaseName => PrefabName;

    /// <inheritdoc/>
    protected override string FullName => "Yarrow";

    /// <inheritdoc/>
    protected override string Description => "Feathery leaves and flat heads of tiny white flowers. Warriors packed it into wounds, and brewers bitter their ale with it.";

    /// <inheritdoc/>
    protected override string CopyItemFrom => "Thistle";

    /// <inheritdoc/>
    protected override string CopyPickableFrom => "Pickable_Dandelion";

    /// <inheritdoc/>
    protected override VegetationConfig Vegetation => new()
    {
        Biome = Heightmap.Biome.Plains,
        Max = 2,
        GroupSizeMin = 2,
        GroupSizeMax = 5,
        GroupRadius = 3f,
        MinAltitude = 1f,
        MaxTilt = 25f,
        ScaleMin = 0.85f,
        ScaleMax = 1.15f,
        BlockCheck = true
    };

    /// <inheritdoc/>
    public override bool Enabled => true;

    /// <inheritdoc/>
    protected override string ExtraDropFrom => "Pickable_Flax_Wild";

    /// <inheritdoc/>
    protected override float ExtraDropChance => 0.2f;

    /// <inheritdoc/>
    protected override void ApplyVisual(GameObject visualRoot)
    {
        ReplacePlantMesh(visualRoot, "yarrow", 0.46f);
    }
}
