using Jotunn.Configs;
using UnityEngine;

namespace BrudvikWhiteHilt.Items.Foraging.RockLichen;

/// <summary>
/// Rock lichen, grey crusts on Mountain stones that were steeped into a purple dye. Model: generated by
/// AssetSource/Tools/make_forage_models.py; the stone stays and the crust grows back. Stone golems are covered in it.
/// </summary>
public class RockLichen : ForageableBase
{
    /// <summary>
    /// Prefab name of the rock lichen item.
    /// </summary>
    public const string PrefabName = "WhiteHiltRockLichen";

    /// <inheritdoc/>
    public override string BaseName => PrefabName;

    /// <inheritdoc/>
    protected override string FullName => "Rock Lichen";

    /// <inheritdoc/>
    protected override string Description => "Grey crusts scraped off mountain stones. Steeped long in lye, they give the purple that kings pay silver for.";

    /// <inheritdoc/>
    protected override string CopyItemFrom => "Thistle";

    /// <inheritdoc/>
    protected override string CopyPickableFrom => "Pickable_Mushroom";

    /// <inheritdoc/>
    protected override VegetationConfig Vegetation => new()
    {
        Biome = Heightmap.Biome.Mountain,
        Max = 1.5f,
        GroupSizeMin = 1,
        GroupSizeMax = 2,
        GroupRadius = 3f,
        MinAltitude = 1f,
        MaxTilt = 40f,
        ScaleMin = 0.9f,
        ScaleMax = 1.3f,
        BlockCheck = true
    };

    /// <inheritdoc/>
    public override bool Enabled => true;

    /// <inheritdoc/>
    protected override string ExtraDropFrom => null;

    /// <inheritdoc/>
    protected override string CreatureDropFrom => "StoneGolem";

    /// <inheritdoc/>
    protected override float CreatureDropChance => 0.5f;

    /// <inheritdoc/>
    protected override void ApplyVisual(GameObject visualRoot)
    {
        ReplacePlantMesh(visualRoot, "rocklichenitem", 0.04f);
    }

    /// <inheritdoc/>
    protected override void ApplyPickableVisual(GameObject pickablePrefab, Pickable pickable)
    {
        ReplaceBushMesh(pickablePrefab, pickable, "rocklichen", 0.16f);
    }
}
