using Jotunn.Configs;
using UnityEngine;

namespace BrudvikWhiteHilt.Items.Foraging.Henbane;

/// <summary>
/// Henbane, a sticky, foul-smelling weed with pale, purple-veined flowers by the Fuling fields of the Plains. A seeress
/// was buried with its seeds, and it was brewed into a maddening beer. Model: generated by
/// AssetSource/Tools/make_forage_models.py. Wild barley picked on the Plains can also give it.
/// </summary>
public class Henbane : ForageableBase
{
    /// <summary>
    /// Prefab name of the henbane item.
    /// </summary>
    public const string PrefabName = "WhiteHiltHenbane";

    /// <inheritdoc/>
    public override string BaseName => PrefabName;

    /// <inheritdoc/>
    protected override string FullName => "Henbane";

    /// <inheritdoc/>
    protected override string Description => "Sticky grey leaves and pale flowers veined with purple, smelling of death. A pinch brings visions; a handful brings madness.";

    /// <inheritdoc/>
    protected override string CopyItemFrom => "Thistle";

    /// <inheritdoc/>
    protected override string CopyPickableFrom => "Pickable_Thistle";

    /// <inheritdoc/>
    protected override VegetationConfig Vegetation => new()
    {
        Biome = Heightmap.Biome.Plains,
        // Groups per zone where the ground suits it; the generator keeps trying spots until they are placed.
        Min = 1,
        Max = 1,
        ForcePlacement = true,
        GroupSizeMin = 1,
        GroupSizeMax = 3,
        GroupRadius = 3f,
        MinAltitude = 1f,
        MaxTilt = 25f,
        ScaleMin = 0.85f,
        ScaleMax = 1.15f,
        BlockCheck = true
    };

    /// <inheritdoc/>
    public override bool Enabled => true;

    /// <inheritdoc/>
    protected override string ExtraDropFrom => "Pickable_Barley_Wild";

    /// <inheritdoc/>
    protected override float ExtraDropChance => 0.1f;

    /// <inheritdoc/>
    protected override float DefaultGroundClearance => 0.1f;

    /// <inheritdoc/>
    protected override void ApplyVisual(GameObject visualRoot)
    {
        ReplacePlantMesh(visualRoot, "henbane", 0.6f);
    }

    /// <inheritdoc/>
    protected override void ApplyPickableVisual(GameObject pickablePrefab, Pickable pickable)
    {
        RemoveGlow(pickablePrefab);
        base.ApplyPickableVisual(pickablePrefab, pickable);
    }
}
