using Jotunn.Configs;
using UnityEngine;

namespace BrudvikWhiteHilt.Items.Foraging.BogBean;

/// <summary>
/// Bog bean, a water plant of the Swamp with three-lobed leaves and fringed white flowers. Bitter enough to brew
/// fever draughts. Model: generated by AssetSource/Tools/make_forage_models.py.
/// Wild turnips picked in the Swamp can also give it.
/// </summary>
public class BogBean : ForageableBase
{
    /// <summary>
    /// Prefab name of the bog bean item.
    /// </summary>
    public const string PrefabName = "WhiteHiltBogBean";

    /// <inheritdoc/>
    public override string BaseName => PrefabName;

    /// <inheritdoc/>
    protected override string FullName => "Bog Bean";

    /// <inheritdoc/>
    protected override string Description => "Three-lobed leaves and fringed white flowers from the edge of the bog water. Bitter as bile, good against fever.";

    /// <inheritdoc/>
    protected override string CopyItemFrom => "Thistle";

    /// <inheritdoc/>
    protected override string CopyPickableFrom => "Pickable_Dandelion";

    /// <inheritdoc/>
    protected override VegetationConfig Vegetation => new()
    {
        Biome = Heightmap.Biome.Swamp,
        Max = 2,
        GroupSizeMin = 2,
        GroupSizeMax = 5,
        GroupRadius = 3f,
        MinAltitude = -0.3f,
        MaxAltitude = 1f,
        MaxTilt = 20f,
        ScaleMin = 0.85f,
        ScaleMax = 1.15f,
        BlockCheck = true
    };

    /// <inheritdoc/>
    public override bool Enabled => true;

    /// <inheritdoc/>
    protected override string ExtraDropFrom => "Pickable_SeedTurnip";

    /// <inheritdoc/>
    protected override void ApplyVisual(GameObject visualRoot)
    {
        ReplacePlantMesh(visualRoot, "bogbean", 0.4f);
    }
}
