using BrudvikWhiteHilt.Helpers;
using Jotunn.Configs;
using UnityEngine;

namespace BrudvikWhiteHilt.Items.Foraging.Ergot;

/// <summary>
/// Ergot, the black horns of a blight on wild barley of the Plains. Bread baked from it brings fits and terrors, and a
/// rune can carry that dread. The pickable is wild barley gone dark with the blight; the item is the horns, generated by
/// AssetSource/Tools/make_forage_models.py. Wild barley picked on the Plains can also give it.
/// </summary>
public class Ergot : ForageableBase
{
    /// <summary>
    /// Prefab name of the ergot item.
    /// </summary>
    public const string PrefabName = "WhiteHiltErgot";

    /// <inheritdoc/>
    public override string BaseName => PrefabName;

    /// <inheritdoc/>
    protected override string FullName => "Ergot";

    /// <inheritdoc/>
    protected override string Description => "Black-purple horns that grow in place of the grain on blighted barley. Bread with it in brings fits and terrors.";

    /// <inheritdoc/>
    protected override string CopyItemFrom => "Thistle";

    /// <inheritdoc/>
    protected override string CopyPickableFrom => "Pickable_Barley_Wild";

    /// <inheritdoc/>
    protected override VegetationConfig Vegetation => new()
    {
        Biome = Heightmap.Biome.Plains,
        Max = 1,
        GroupSizeMin = 2,
        GroupSizeMax = 4,
        GroupRadius = 3f,
        MinAltitude = 1f,
        MaxTilt = 20f,
        ScaleMin = 0.9f,
        ScaleMax = 1.1f,
        BlockCheck = true
    };

    /// <inheritdoc/>
    public override bool Enabled => true;

    /// <inheritdoc/>
    protected override string ExtraDropFrom => "Pickable_Barley_Wild";

    /// <inheritdoc/>
    protected override float ExtraDropChance => 0.15f;

    /// <inheritdoc/>
    protected override void ApplyVisual(GameObject visualRoot)
    {
        if (IsItem(visualRoot))
        {
            ReplacePlantMesh(visualRoot, "ergot", 0.02f);
            return;
        }

        // Golden barley turns a dark, blighted purple-brown.
        VisualHelper.RecolorHue(visualRoot, 0.04f, 0.2f, 0.85f, 0.45f, 0.45f);
    }
}
