using System;
using System.IO;
using System.Linq;
using UnityEngine;

namespace BrudvikWhiteHilt.Pieces.Defenses;

/// <summary>
/// The defence pieces as generated by AssetSource/Preview/build_defenses.py. The same file drives the preview renders,
/// so what the previews show is what the game builds.
/// </summary>
[Serializable]
public class DefenseLayout
{
    private const string ResourceName = "BrudvikWhiteHilt.Defenses.json";

    private static DefenseLayout loaded;

    /// <summary>
    /// Every piece and template in the layout.
    /// </summary>
    public DefensePieceData[] pieces;

    /// <summary>
    /// Loads the embedded layout once.
    /// </summary>
    /// <returns>The layout.</returns>
    public static DefenseLayout Load()
    {
        if (loaded != null)
        {
            return loaded;
        }

        using Stream stream = typeof(DefenseLayout).Assembly.GetManifestResourceStream(ResourceName)
            ?? throw new InvalidOperationException($"Embedded resource '{ResourceName}' not found.");
        using StreamReader reader = new(stream);
        loaded = JsonUtility.FromJson<DefenseLayout>(reader.ReadToEnd());
        return loaded;
    }

    /// <summary>
    /// Returns a piece or template by name.
    /// </summary>
    /// <param name="name">Name in the layout.</param>
    /// <returns>The piece.</returns>
    public DefensePieceData Get(string name)
    {
        return pieces.FirstOrDefault(piece => piece.name == name) ?? throw new InvalidOperationException($"The defence layout has no piece '{name}'.");
    }
}

/// <summary>
/// One piece or template of the defence layout.
/// </summary>
[Serializable]
public class DefensePieceData
{
    /// <summary>Name in the layout.</summary>
    public string name;

    /// <summary>Vanilla piece the game piece is cloned from.</summary>
    public string @base;

    /// <summary>The meshes the piece is made of.</summary>
    public DefensePartData[] parts;

    /// <summary>Box colliders.</summary>
    public DefenseBoxData[] colliders;

    /// <summary>Snap points, three floats each.</summary>
    public float[] snapPoints;

    /// <summary>Ladders that carry players between floors.</summary>
    public DefenseLadderData[] ladders;

    /// <summary>Parts that move together around a pivot, such as gate leaves.</summary>
    public DefenseGroupData[] groups;

    /// <summary>Children of the vanilla piece that are kept, such as the gate's animated door.</summary>
    public string[] keep;

    /// <summary>Area where the piece hurts creatures, for pieces cloned from the sharp stakes.</summary>
    public DefenseBoxData hitArea;
}

/// <summary>
/// One mesh, or a nested template, placed in a piece.
/// </summary>
[Serializable]
public class DefensePartData
{
    /// <summary>Vanilla mesh key, see <see cref="VanillaMeshLibrary"/>.</summary>
    public string mesh;

    /// <summary>Template placed instead of a mesh.</summary>
    public string piece;

    /// <summary>Position in metres.</summary>
    public float[] position;

    /// <summary>Euler rotation in degrees.</summary>
    public float[] rotation;

    /// <summary>Scale.</summary>
    public float[] scale;

    /// <summary>Colour multiplied into the material, or null.</summary>
    public float[] tint;

    /// <summary>Texture name of a vanilla material to use instead of the mesh's own, or null.</summary>
    public string texture;

    /// <summary>Moving group the part belongs to, or null.</summary>
    public string group;

    /// <summary>Small detail that is dropped at a distance and casts no shadow.</summary>
    public bool detail;
}

/// <summary>
/// A box, used for colliders and hit areas.
/// </summary>
[Serializable]
public class DefenseBoxData
{
    /// <summary>Centre in metres.</summary>
    public float[] center;

    /// <summary>Size in metres.</summary>
    public float[] size;

    /// <summary>Euler rotation in degrees.</summary>
    public float[] rotation;

    /// <summary>Moving group the box belongs to, or null.</summary>
    public string group;
}

/// <summary>
/// A ladder: the box players look at and the points it carries them between.
/// </summary>
[Serializable]
public class DefenseLadderData
{
    /// <summary>Centre of the ladder box.</summary>
    public float[] center;

    /// <summary>Size of the ladder box.</summary>
    public float[] size;

    /// <summary>Stops from bottom to top, three floats each.</summary>
    public float[] stops;
}

/// <summary>
/// Parts that move together, such as a gate leaf turning on its hinge.
/// </summary>
[Serializable]
public class DefenseGroupData
{
    /// <summary>Group name used by parts and colliders.</summary>
    public string name;

    /// <summary>Hinge position.</summary>
    public float[] pivot;

    /// <summary>Turns the opposite way of the vanilla door.</summary>
    public bool mirror;
}
