using System;
using System.IO;
using System.Linq;

namespace BrudvikWhiteHilt.Pieces.Defenses;

/// <summary>
/// The defence pieces as generated by AssetSource/Preview/build_defenses.py. The same file drives the preview renders,
/// so what the previews show is what the game builds.
/// </summary>
/// <remarks>
/// The pieces are data, not code: each lists the vanilla meshes it is made of (with position, rotation, scale, tint
/// and texture), its colliders, snap points, ladders and moving groups. <see cref="DefensePieceBase"/> turns an entry
/// into a game piece, combining the meshes per material (<see cref="DefenseModelBuilder"/>). New shapes are made by
/// changing the Python generator, not the C# code; the tests in LayoutTests check the file against what the code
/// expects of it.
/// </remarks>
[Serializable]
public class DefenseLayout
{
    private const string ResourceName = "BrudvikWhiteHilt.Defenses.json";

    private static DefenseLayout loaded;

    /// <summary>
    /// Every piece and template in the layout.
    /// </summary>
    public DefensePieceData[] pieces;

    /// <summary>
    /// Loads the embedded layout once.
    /// </summary>
    /// <returns>The layout.</returns>
    public static DefenseLayout Load()
    {
        if (loaded != null)
        {
            return loaded;
        }

        using Stream stream = typeof(DefenseLayout).Assembly.GetManifestResourceStream(ResourceName)
            ?? throw new InvalidOperationException($"Embedded resource '{ResourceName}' not found.");
        using StreamReader reader = new(stream);

        // Unity's JsonUtility left every field empty for the mod's types in game; Jotunn's SimpleJson fills them by reflection.
        loaded = SimpleJson.SimpleJson.DeserializeObject<DefenseLayout>(reader.ReadToEnd());
        if (loaded?.pieces == null || loaded.pieces.Length == 0)
        {
            throw new InvalidOperationException($"Embedded resource '{ResourceName}' has no pieces.");
        }

        loaded.pieces = loaded.pieces.Select(piece => piece.of == null ? piece : loaded.Expand(piece)).ToArray();
        return loaded;
    }

    // A variant is its plain piece with other textures and tints, and parts of its own: the black marble and grausten
    // stone defences, written that way so the layout read at every start holds each shape once.
    private DefensePieceData Expand(DefensePieceData variant)
    {
        DefensePieceData plain = Get(variant.of);
        return new DefensePieceData
        {
            name = variant.name,
            @base = plain.@base,
            parts = plain.parts.Select(part => variant.Restyle(part)).Concat(variant.extraParts ?? Array.Empty<DefensePartData>()).ToArray(),
            colliders = plain.colliders,
            snapPoints = plain.snapPoints,
            ladders = plain.ladders,
            groups = plain.groups,
            keep = plain.keep,
            hitArea = plain.hitArea
        };
    }

    /// <summary>
    /// Returns a piece or template by name.
    /// </summary>
    /// <param name="name">Name in the layout.</param>
    /// <returns>The piece.</returns>
    /// <exception cref="InvalidOperationException">The layout has no piece of that name.</exception>
    public DefensePieceData Get(string name)
    {
        return pieces.FirstOrDefault(piece => piece.name == name) ?? throw new InvalidOperationException($"The defence layout has no piece '{name}'.");
    }
}

/// <summary>
/// One piece or template of the defence layout.
/// </summary>
[Serializable]
public class DefensePieceData
{
    /// <summary>Name in the layout.</summary>
    public string name;

    /// <summary>Vanilla piece the game piece is cloned from.</summary>
    public string @base;

    /// <summary>The meshes the piece is made of.</summary>
    public DefensePartData[] parts;

    /// <summary>Box colliders.</summary>
    public DefenseBoxData[] colliders;

    /// <summary>Snap points, three floats each.</summary>
    public float[] snapPoints;

    /// <summary>Ladders that carry players between floors.</summary>
    public DefenseLadderData[] ladders;

    /// <summary>Parts that move together around a pivot, such as gate leaves.</summary>
    public DefenseGroupData[] groups;

    /// <summary>Children of the vanilla piece that are kept, such as the gate's animated door.</summary>
    public string[] keep;

    /// <summary>Area where the piece hurts creatures, for pieces cloned from the sharp stakes.</summary>
    public DefenseBoxData hitArea;

    /// <summary>
    /// For a variant, the plain piece it is built on; null for a piece written out in full. A variant gives only what
    /// differs (<see cref="textures"/>, <see cref="tints"/>, <see cref="extraParts"/>) and is expanded when the layout
    /// is
    /// loaded, so the file holds each shape once.
    /// </summary>
    public string of;

    /// <summary>For a variant: the texture each mesh takes instead of the plain piece's.</summary>
    public DefenseTextureData[] textures;

    /// <summary>For a variant: tints swapped mesh by mesh.</summary>
    public DefenseTintData[] tints;

    /// <summary>For a variant: parts only it has, such as grausten's iron spikes.</summary>
    public DefensePartData[] extraParts;

    // A part of the plain piece in this variant's texture and tints.
    internal DefensePartData Restyle(DefensePartData part)
    {
        string texture = textures?.FirstOrDefault(entry => entry.mesh == part.mesh)?.texture ?? part.texture;
        float[] tint = tints?.FirstOrDefault(entry => entry.mesh == part.mesh && Same(entry.from, part.tint))?.to ?? part.tint;
        return new DefensePartData
        {
            mesh = part.mesh,
            piece = part.piece,
            position = part.position,
            rotation = part.rotation,
            scale = part.scale,
            tint = tint,
            texture = texture,
            group = part.group,
            detail = part.detail
        };
    }

    private static bool Same(float[] a, float[] b)
    {
        int lengthA = a?.Length ?? 0;
        int lengthB = b?.Length ?? 0;
        return lengthA == lengthB && Enumerable.Range(0, lengthA).All(i => Math.Abs(a[i] - b[i]) < 0.0005f);
    }
}

/// <summary>
/// The texture a variant gives every part of one mesh, e.g. the black marble on the stone blocks.
/// </summary>
[Serializable]
public class DefenseTextureData
{
    /// <summary>Mesh key of the parts it applies to.</summary>
    public string mesh;

    /// <summary>Name of the vanilla texture they take.</summary>
    public string texture;
}

/// <summary>
/// A tint a variant swaps for another on the parts of one mesh, e.g. the damp lower courses of grausten.
/// </summary>
[Serializable]
public class DefenseTintData
{
    /// <summary>Mesh key of the parts it applies to.</summary>
    public string mesh;

    /// <summary>The plain piece's tint that is replaced.</summary>
    public float[] from;

    /// <summary>The variant's tint.</summary>
    public float[] to;
}

/// <summary>
/// One mesh, or a nested template, placed in a piece.
/// </summary>
[Serializable]
public class DefensePartData
{
    /// <summary>Vanilla mesh key, see <see cref="VanillaMeshLibrary"/>.</summary>
    public string mesh;

    /// <summary>Template placed instead of a mesh.</summary>
    public string piece;

    /// <summary>Position in metres.</summary>
    public float[] position;

    /// <summary>Euler rotation in degrees.</summary>
    public float[] rotation;

    /// <summary>Scale.</summary>
    public float[] scale;

    /// <summary>Colour multiplied into the material, or null.</summary>
    public float[] tint;

    /// <summary>Texture name of a vanilla material to use instead of the mesh's own, or null.</summary>
    public string texture;

    /// <summary>Moving group the part belongs to, or null.</summary>
    public string group;

    /// <summary>Small detail that is dropped at a distance and casts no shadow.</summary>
    public bool detail;
}

/// <summary>
/// A box, used for colliders and hit areas.
/// </summary>
[Serializable]
public class DefenseBoxData
{
    /// <summary>Centre in metres.</summary>
    public float[] center;

    /// <summary>Size in metres.</summary>
    public float[] size;

    /// <summary>Euler rotation in degrees.</summary>
    public float[] rotation;

    /// <summary>Moving group the box belongs to, or null.</summary>
    public string group;
}

/// <summary>
/// A ladder: the box players look at and the points it carries them between.
/// </summary>
[Serializable]
public class DefenseLadderData
{
    /// <summary>Centre of the ladder box.</summary>
    public float[] center;

    /// <summary>Size of the ladder box.</summary>
    public float[] size;

    /// <summary>Stops from bottom to top, three floats each.</summary>
    public float[] stops;
}

/// <summary>
/// Parts that move together, such as a gate leaf turning on its hinge.
/// </summary>
[Serializable]
public class DefenseGroupData
{
    /// <summary>Group name used by parts and colliders.</summary>
    public string name;

    /// <summary>Hinge position.</summary>
    public float[] pivot;

    /// <summary>Turns the opposite way of the vanilla door.</summary>
    public bool mirror;
}
