using Jotunn.Configs;
using UnityEngine;

namespace BrudvikWhiteHilt.Items.Foraging.Meadowsweet;

/// <summary>
/// Meadowsweet, tall stems with frothy cream flowers on the damp edges of the Swamp. Its name says what it was for:
/// sweetening mead, and it eases pain. Model: generated by AssetSource/Tools/make_forage_models.py.
/// Wild turnips picked in the Swamp can also give it.
/// </summary>
public class Meadowsweet : ForageableBase
{
    /// <summary>
    /// Prefab name of the meadowsweet item.
    /// </summary>
    public const string PrefabName = "WhiteHiltMeadowsweet";

    /// <inheritdoc/>
    public override string BaseName => PrefabName;

    /// <inheritdoc/>
    protected override string FullName => "Meadowsweet";

    /// <inheritdoc/>
    protected override string Description => "Frothy cream flowers on red stems, smelling of honey and almonds. Brewers sweeten mead with it, and it dulls an aching head.";

    /// <inheritdoc/>
    protected override string CopyItemFrom => "Thistle";

    /// <inheritdoc/>
    protected override string CopyPickableFrom => "Pickable_Thistle";

    /// <inheritdoc/>
    protected override VegetationConfig Vegetation => new()
    {
        Biome = Heightmap.Biome.Swamp,
        Max = 2,
        GroupSizeMin = 2,
        GroupSizeMax = 4,
        GroupRadius = 3f,
        MinAltitude = 0.3f,
        MaxTilt = 20f,
        ScaleMin = 0.85f,
        ScaleMax = 1.15f,
        BlockCheck = true
    };

    /// <inheritdoc/>
    public override bool Enabled => true;

    /// <inheritdoc/>
    protected override string ExtraDropFrom => "Pickable_SeedTurnip";

    /// <inheritdoc/>
    protected override float ExtraDropChance => 0.2f;

    /// <inheritdoc/>
    protected override void ApplyVisual(GameObject visualRoot)
    {
        ReplacePlantMesh(visualRoot, "meadowsweet", 1.15f);
    }

    /// <inheritdoc/>
    protected override void ApplyPickableVisual(GameObject pickablePrefab, Pickable pickable)
    {
        RemoveGlow(pickablePrefab);
        base.ApplyPickableVisual(pickablePrefab, pickable);
    }
}
