using BrudvikWhiteHilt.Helpers;
using Jotunn.Configs;
using UnityEngine;

namespace BrudvikWhiteHilt.Items.Foraging.Rosehips;

/// <summary>
/// Rosehips, the red fruit of the dog rose on the Plains. Model: generated by AssetSource/Tools/make_forage_models.py;
/// the hips hide when picked. Cloudberry bushes picked on the Plains can also give them.
/// </summary>
public class Rosehips : ForageableBase
{
    /// <summary>
    /// Prefab name of the rosehips item.
    /// </summary>
    public const string PrefabName = "WhiteHiltRosehips";

    /// <inheritdoc/>
    public override string BaseName => PrefabName;

    /// <inheritdoc/>
    protected override string FullName => "Rosehips";

    /// <inheritdoc/>
    protected override string Description => "Glossy red hips from the thorny dog rose. Sour and sweet at once, and full of the summer through the winter.";

    /// <inheritdoc/>
    protected override string CopyItemFrom => "Raspberry";

    /// <inheritdoc/>
    protected override string CopyPickableFrom => "RaspberryBush";

    /// <inheritdoc/>
    protected override VegetationConfig Vegetation => new()
    {
        Biome = Heightmap.Biome.Plains,
        // Groups per zone where the ground suits it; the generator keeps trying spots until they are placed.
        Min = 1,
        Max = 2,
        ForcePlacement = true,
        GroupSizeMin = 1,
        GroupSizeMax = 3,
        GroupRadius = 4f,
        MinAltitude = 1f,
        MaxTilt = 25f,
        ScaleMin = 0.85f,
        ScaleMax = 1.15f,
        BlockCheck = true
    };

    /// <inheritdoc/>
    public override bool Enabled => true;

    /// <inheritdoc/>
    protected override string ExtraDropFrom => "CloudberryBush";

    /// <inheritdoc/>
    protected override void ApplyVisual(GameObject visualRoot)
    {
        // Raspberries turn the orange-red of rosehips.
        VisualHelper.RecolorHue(visualRoot, 0.85f, 1f, 0.03f, 1.1f, 1.05f);
    }

    /// <inheritdoc/>
    protected override void ApplyPickableVisual(GameObject pickablePrefab, Pickable pickable)
    {
        ReplaceBushMesh(pickablePrefab, pickable, "rosehip", 1f);
    }
}
