using BrudvikWhiteHilt.Helpers;
using Jotunn.Configs;
using UnityEngine;

namespace BrudvikWhiteHilt.Items.Foraging.Juniper;

/// <summary>
/// Juniper berries, from the prickly juniper shrubs of the Mountains. Juniper smoke was burnt to drive away spirits, so
/// the berries etch a rune against the dead. Model: generated by AssetSource/Tools/make_forage_models.py; the berries hide
/// when picked. Wild onions picked in the Mountains can also give them.
/// </summary>
public class Juniper : ForageableBase
{
    /// <summary>
    /// Prefab name of the juniper berries item.
    /// </summary>
    public const string PrefabName = "WhiteHiltJuniper";

    /// <inheritdoc/>
    public override string BaseName => PrefabName;

    /// <inheritdoc/>
    protected override string FullName => "Juniper Berries";

    /// <inheritdoc/>
    protected override string Description => "Blue-dusted, bitter berries from the prickly mountain juniper. Juniper smoke is said to keep spirits and the restless dead away.";

    /// <inheritdoc/>
    protected override string CopyItemFrom => "Blueberries";

    /// <inheritdoc/>
    protected override string CopyPickableFrom => "BlueberryBush";

    /// <inheritdoc/>
    protected override VegetationConfig Vegetation => new()
    {
        Biome = Heightmap.Biome.Mountain,
        Max = 1.5f,
        GroupSizeMin = 1,
        GroupSizeMax = 2,
        GroupRadius = 4f,
        MinAltitude = 1f,
        MaxTilt = 35f,
        ScaleMin = 0.8f,
        ScaleMax = 1.2f,
        BlockCheck = true
    };

    /// <inheritdoc/>
    public override bool Enabled => true;

    /// <inheritdoc/>
    protected override string ExtraDropFrom => "Pickable_SeedOnion";

    /// <inheritdoc/>
    protected override float ExtraDropChance => 0.2f;

    /// <inheritdoc/>
    protected override void ApplyVisual(GameObject visualRoot)
    {
        // Blueberries turn the dusty grey-blue of juniper berries.
        VisualHelper.RecolorHue(visualRoot, 0.55f, 0.8f, 0.6f, 0.45f, 1.1f);
    }

    /// <inheritdoc/>
    protected override void ApplyPickableVisual(GameObject pickablePrefab, Pickable pickable)
    {
        ReplaceBushMesh(pickablePrefab, pickable, "juniper", 0.95f);
    }
}
