using Jotunn.Configs;
using UnityEngine;

namespace BrudvikWhiteHilt.Items.Foraging.WildHops;

/// <summary>
/// Wild hops, a vine twined up an old stake on the Plains with pale green cones. Brewed in, they make ale keep and make
/// the drinker sleepy. Model: generated by AssetSource/Tools/make_forage_models.py; the stake and vine stay and the cones
/// grow back. Cloudberry bushes picked on the Plains can also give them.
/// </summary>
public class WildHops : ForageableBase
{
    /// <summary>
    /// Prefab name of the hop cones item.
    /// </summary>
    public const string PrefabName = "WhiteHiltHops";

    /// <inheritdoc/>
    public override string BaseName => PrefabName;

    /// <inheritdoc/>
    protected override string FullName => "Hop Cones";

    /// <inheritdoc/>
    protected override string Description => "Papery green cones of the wild hop vine, sticky with bitter yellow dust. Ale brewed with them keeps, and puts you to sleep.";

    /// <inheritdoc/>
    protected override string CopyItemFrom => "Thistle";

    /// <inheritdoc/>
    protected override string CopyPickableFrom => "Pickable_Thistle";

    /// <inheritdoc/>
    protected override VegetationConfig Vegetation => new()
    {
        Biome = Heightmap.Biome.Plains,
        Max = 1,
        GroupSizeMin = 1,
        GroupSizeMax = 2,
        GroupRadius = 4f,
        MinAltitude = 1f,
        MaxTilt = 20f,
        ScaleMin = 0.9f,
        ScaleMax = 1.1f,
        BlockCheck = true
    };

    /// <inheritdoc/>
    public override bool Enabled => true;

    /// <inheritdoc/>
    protected override string ExtraDropFrom => "CloudberryBush";

    /// <inheritdoc/>
    protected override float ExtraDropChance => 0.1f;

    /// <inheritdoc/>
    protected override void ApplyVisual(GameObject visualRoot)
    {
        ReplacePlantMesh(visualRoot, "hopcones", 0.07f);
    }

    /// <inheritdoc/>
    protected override void ApplyPickableVisual(GameObject pickablePrefab, Pickable pickable)
    {
        RemoveGlow(pickablePrefab);
        ReplaceBushMesh(pickablePrefab, pickable, "hops", 1.55f);
    }
}
