using BepInEx.Configuration;
using BrudvikWhiteHilt.Progression;
using Jotunn.Configs;
using Jotunn.Entities;
using Jotunn.Managers;
using UnityEngine;

namespace BrudvikWhiteHilt.Items.Foraging.Peat;

/// <summary>
/// Peat, cut from the drier banks of the Swamp and stacked to dry. It burns long in a wood fire and the charcoal kiln
/// turns it into coal. Model: generated by AssetSource/Tools/make_forage_models.py.
/// </summary>
public class Peat : ForageableBase
{
    /// <summary>
    /// Prefab name of the peat item.
    /// </summary>
    public const string PrefabName = "WhiteHiltPeat";

    private static ConfigEntry<float> fuelValue;

    /// <summary>
    /// Creates the definition. The plugin does this for every such class by reflection when it starts; the game sees
    /// the result only once Add has run. Binds the fuel setting.
    /// </summary>
    public Peat()
    {
        fuelValue = WhiteHiltConfig.BindAdminOnly("Foraging.Peat", "FuelValue", 2f,
            "How much wood one brick of peat is worth in a wood fire (campfire, hearth, bonfire). Use it from the hotbar on the fire.",
            new AcceptableValueRange<float>(0.5f, 10f));
    }

    /// <summary>
    /// How much wood one brick is worth in a fire.
    /// </summary>
    public static float FuelValue => fuelValue?.Value ?? 2f;

    /// <inheritdoc/>
    public override string BaseName => PrefabName;

    /// <inheritdoc/>
    protected override string FullName => "Peat";

    /// <inheritdoc/>
    protected override string Description => "A dark brick of cut bog turf, dried in a stack. It smoulders long and hot in a wood fire, and the kiln makes coal of it.";

    /// <inheritdoc/>
    protected override string CopyItemFrom => "Coal";

    /// <inheritdoc/>
    protected override string CopyPickableFrom => "Pickable_Stone";

    /// <inheritdoc/>
    protected override VegetationConfig Vegetation => new()
    {
        Biome = Heightmap.Biome.Swamp,
        Max = 1.5f,
        GroupSizeMin = 1,
        GroupSizeMax = 2,
        GroupRadius = 3f,
        MinAltitude = 0.5f,
        MaxTilt = 15f,
        ScaleMin = 0.9f,
        ScaleMax = 1.1f,
        BlockCheck = true
    };

    /// <inheritdoc/>
    public override bool Enabled => true;

    /// <inheritdoc/>
    protected override string ExtraDropFrom => null;

    /// <inheritdoc/>
    protected override float DefaultGroundClearance => 0.1f;

    /// <inheritdoc/>
    protected override void ApplyVisual(GameObject visualRoot)
    {
        ReplacePlantMesh(visualRoot, IsItem(visualRoot) ? "peatbrick" : "peatstack", 0.3f);
    }

    /// <inheritdoc/>
    protected override void OnAdded()
    {
        ItemManager.Instance.AddItemConversion(new CustomItemConversion(new SmelterConversionConfig
        {
            Station = Smelters.CharcoalKiln,
            FromItem = PrefabName,
            ToItem = "Coal"
        }));
    }
}
