using Jotunn.Configs;
using UnityEngine;

namespace BrudvikWhiteHilt.Items.Foraging.Cattail;

/// <summary>
/// Cattail, tall bog grass with brown velvet heads at the water's edge in the Swamp. Its roots are dried and ground into
/// a coarse flour. Model: generated by AssetSource/Tools/make_forage_models.py.
/// Wild turnips picked in the Swamp can also give it.
/// </summary>
public class Cattail : ForageableBase
{
    /// <summary>
    /// Prefab name of the cattail item.
    /// </summary>
    public const string PrefabName = "WhiteHiltCattail";

    /// <inheritdoc/>
    public override string BaseName => PrefabName;

    /// <inheritdoc/>
    protected override string FullName => "Cattail";

    /// <inheritdoc/>
    protected override string Description => "Tall bog grass with brown, velvety heads. The starchy roots are dried and ground into a coarse flour.";

    /// <inheritdoc/>
    protected override string CopyItemFrom => "Flax";

    /// <inheritdoc/>
    protected override string CopyPickableFrom => "Pickable_Flax_Wild";

    /// <inheritdoc/>
    protected override VegetationConfig Vegetation => new()
    {
        Biome = Heightmap.Biome.Swamp,
        Max = 2,
        GroupSizeMin = 3,
        GroupSizeMax = 6,
        GroupRadius = 3f,
        MinAltitude = -0.8f,
        MaxAltitude = 0.5f,
        MaxTilt = 25f,
        ScaleMin = 0.9f,
        ScaleMax = 1.2f,
        BlockCheck = true
    };

    /// <inheritdoc/>
    public override bool Enabled => true;

    /// <inheritdoc/>
    protected override string ExtraDropFrom => "Pickable_SeedTurnip";

    /// <inheritdoc/>
    protected override float ExtraDropChance => 0.2f;

    /// <inheritdoc/>
    protected override void ApplyVisual(GameObject visualRoot)
    {
        ReplacePlantMesh(visualRoot, "cattail", 1.6f);
    }
}
